### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Sang-ATTN-UIT** [mehmedkadric/random-string-detector#4]
i run your code in lastest version now (1.0.2) and got the rerror:
Traceback (most recent call last):
  File ".../Lib/site-packages/random_string_detector/detector.py", line 4, in <module>
    from random_string_detector.bigrams import ENGLISH
  File ".../\lib\site-packages\random_string_detector\__init__.py", line 2, in <module>
    from random_string_detector.detector import RandomStringDetector
  File ".../\lib\site-packages\random_string_detector\detector.py", line 7, in <module>
    class RandomStringDetector(object):
  File ".../\site-packages\random_string_detector\detector.py", line 12, in RandomStringDetector
    bigrams_probs: Union[MappingProxyType[str,
TypeError: 'type' object is not subscriptable

**Comment by mehmedkadric** [comment]
Could you please provide code example and your Python version? I am not able to reproduce the issue.

**Comment by mehmedkadric** [comment]
Requirement updated in https://pypi.org/project/random-string-detector/1.0.3/.

Thank you.
